sudo: false
language: java

jdk:
- oraclejdk8
- oraclejdk7
- openjdk7

before_install:
  - git submodule update --init --recursive

script: ant dist

env:
  global:
    secure: Df5FIHnieDJj8AAwgeAh779Rs+aoJ8e9WQN0ero4OfcJ2Y1G7InBZQIGesfVR1M7EX4Hf0fvmUam9zthdwi4culk+gJeOAMM/wpCqvEUyWDTd78Cr08L7PjNW8RCq5NCYhgvO1j+IzJOA3IR6h8DSS4QGZtJqPYk65ZQ1uRyAGc=

addons:
  coverity_scan:
    project:
      name: martinpaljak/GlobalPlatformPro
      description: GlobalPlatformPro from javacard.pro
    notification_email: martin@martinpaljak.net
    build_command_prepend: 
    build_command: ant compile
    branch_pattern: coverity
